vinylstore/config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/index'

  devise_for :users
  root to: "static_pages#home"
  resources :items
  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'

  get 'static_pages/profile'

  get '/catalog', to: 'items#index'

  get '/search', to: 'static_pages#search'

  get '/cart', to: 'static_pages#cart'

  get 'static_pages/checkout'

  get 'static_pages/confirmation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

vinylstore/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

vinylstore/app/models/item.rb
class Item < ApplicationRecord
end

vinylstore/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

vinylstore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
 
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

vinylstore/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:artist, :title, :price, :image_url, :genre, :label, :year)
    end
end

vinylstore/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new]
 
  def index
  end
 
  def new
  end
end

vinylstore/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def register
  end

  def login
  end

  def profile
  end

  def catalog
  end

  def search
  end

  def cart
  end

  def checkout
  end

  def confirmation
  end
end

vinylstore/app/helpers/application_helper.rb
module ApplicationHelper
end

vinylstore/app/helpers/items_helper.rb
module ItemsHelper
end

vinylstore/app/helpers/pages_helper.rb
module PagesHelper
end

vinylstore/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

vinylstore/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :item_artist %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :item_image_url %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :item_genre %>
  </div>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label, id: :item_label %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :item_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

vinylstore/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

vinylstore/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catalogue</h1>
     <% @items.each do |item| %>
<div class="jumbotron">
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-block">
      <img class="card-img" alt="Card image cap" src = <%= item.image_url %> >
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-block">
  <table class="table">
    <thead>
      <tr>
        <th>Artist</th>
        <th>Title</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= item.artist %></td>
        <td><%= item.title %></td>
        <td><%= item.price %></td>
      </tr>
</tbody>
<tr>
  <th colspan="3"><br></th>
</tr>
     <thead>
      <tr>
        <th>Genre</th>
        <th>Label</th>
        <th>Year</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= item.genre %></td>
        <td><%= item.label %></td>
        <td><%= item.year %></td>
        
      </tr>
   <tr>
  <th colspan="3"><br></th>
</tr>
        <td><button class="btn btn-success btn-sm"><%= link_to 'Show', item %></button></td>
        <td><button class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_item_path(item) %></button></td>
        <td><button class="btn btn-danger btn-sm"><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
   
    
  </tbody>
  
</table>

      </div>
    </div>
  </div>
</div>

</div>
<% end %>


<button class="btn btn-success"><%= link_to 'New Item', new_item_path %></button>

vinylstore/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

vinylstore/app/views/items/show.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @item.artist %>
</p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @item.genre %>
</p>

<p>
  <strong>Label:</strong>
  <%= @item.label %>
</p>

<p>
  <strong>Year:</strong>
  <%= @item.year %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>
</div>

vinylstore/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Good Vibrations Vinyl 2017
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      
    </ul>
  </nav>
</footer>

vinylstore/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse metal_header">
  <div class="container">
    <h4 id="logo">Good Vibrations Vinyl</h4>
    <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Browse", catalog_path %></li>
            <li><%= link_to "Search", search_path %></li>
            <li><%= link_to "Shopping Cart", cart_path %></li>

        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
 </div>
</header>

vinylstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | GoodVibrationsVinyl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
    </div>
  <%=render 'layouts/footer'%> 
  </body>
</html>

vinylstore/app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

vinylstore/app/views/static_pages/cart.html.erb
<% provide(:title, "Cart") %>
<h1>Shopping Cart</h1>

vinylstore/app/views/static_pages/catalog.html.erb
<% provide(:title, "Catalog") %>
<h1>Catalog</h1>

vinylstore/app/views/static_pages/checkout.html.erb
<% provide(:title, "Checkout") %>
<h1>Checkout</h1>

vinylstore/app/views/static_pages/confirmation.html.erb
<% provide(:title, "Confirmation") %>
<h1>Confirmation</h1>

vinylstore/app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Popular Titles</h1>

<div class="container">    
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading">Pink Floyd - Dark Side of the Moon</div>
        <div class="panel-body"><%= image_tag("dark.jpg", alt:"Image")%></div>
        <div class="panel-footer">€19.99</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-primary">
        <div class="panel-heading">Fleetwood Mac - Rumours</div>
        <div class="panel-body"><%= image_tag("rumours.jpg", alt:"Image")%></div>
        <div class="panel-footer">€21.99</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-primary">
        <div class="panel-heading">Neil Young - Harvest</div>
        <div class="panel-body"><%= image_tag("harvest.jpg", alt:"Image")%></div>
        <div class="panel-footer">€24.99</div>
      </div>
    </div>
  </div>
  
  </div><br>

<div class="container">    
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading">Led Zeppelin - I</div>
        <div class="panel-body"><%= image_tag("led.png", alt:"Image")%></div>
        <div class="panel-footer">€19.99</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-primary">
        <div class="panel-heading">The Strokes - Is This It</div>
        <div class="panel-body"><%= image_tag("isthisit.jpg", alt:"Image")%></div>
        <div class="panel-footer">€19.99</div>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-primary">
        <div class="panel-heading">Bob Dylan - Blonde on Blonde</div>
        <div class="panel-body"><%= image_tag("blonde.jpg", alt:"Image")%></div>
        <div class="panel-footer">€19.99</div>
      </div>
    </div>
  </div>
</div><br><br>

vinylstore/app/views/static_pages/login.html.erb
<% provide(:title, "Login") %>
<h1>Log In</h1>

vinylstore/app/views/static_pages/profile.html.erb
<% provide(:title, "Profile") %>
<h1>Profile</h1>

vinylstore/app/views/static_pages/register.html.erb
<% provide(:title, "Register") %>
<h1>Register</h1>

vinylstore/app/views/static_pages/search.html.erb
<% provide(:title, "Search") %>
<h1>Search</h1>